-- MySQL Script generated by MySQL Workbench
-- Ter 27 Fev 2018 14:24:43 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bd_auto1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_auto1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_auto1` DEFAULT CHARACTER SET utf8 ;
USE `bd_auto1` ;

-- -----------------------------------------------------
-- Table `bd_auto1`.`MONTADORA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_auto1`.`MONTADORA` (
  `idmontadora` INT(11) NOT NULL,
  `MONTADORA` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idmontadora`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_auto1`.`especificacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_auto1`.`especificacao` (
  `idespecificacao` INT NOT NULL AUTO_INCREMENT,
  `potencia` VARCHAR(45) NULL,
  `portas` VARCHAR(45) NULL,
  `preco` VARCHAR(45) NULL,
  `altura` VARCHAR(45) NULL,
  ` largura` VARCHAR(45) NULL,
  `comprimento` VARCHAR(45) NULL,
  `cambio` VARCHAR(45) NULL,
  `velocidade` VARCHAR(45) NULL,
  `tanque_combustivel` VARCHAR(45) NULL,
  `tip_combustivel` VARCHAR(45) NULL,
  `portas_malas` VARCHAR(45) NULL,
  `tip_direcao` VARCHAR(45) NULL,
  `consumo_urb` VARCHAR(45) NULL,
  `consumo_rod` VARCHAR(45) NULL,
  `marcha` VARCHAR(45) NULL,
  `tip_tracao` VARCHAR(45) NULL,
  `tip_veiculo` VARCHAR(45) NULL,
  `porte` VARCHAR(45) NULL,
  `ocupantes` VARCHAR(45) NULL,
  `tip_freio` VARCHAR(45) NULL,
  PRIMARY KEY (`idespecificacao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_auto1`.`carro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_auto1`.`carro` (
  `idcarro` INT(11) NOT NULL,
  `carro` VARCHAR(45) NULL DEFAULT NULL,
  `idmontadora` INT(11) NOT NULL,
  `especificacao_idespecificacao` INT NOT NULL,
  PRIMARY KEY (`idcarro`),
  INDEX `fk_carro_MONTADORA_idx` (`idmontadora` ASC),
  INDEX `fk_carro_especificacao1_idx` (`especificacao_idespecificacao` ASC),
  CONSTRAINT `fk_carro_MONTADORA`
    FOREIGN KEY (`idmontadora`)
    REFERENCES `bd_auto1`.`MONTADORA` (`idmontadora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_carro_especificacao1`
    FOREIGN KEY (`especificacao_idespecificacao`)
    REFERENCES `bd_auto1`.`especificacao` (`idespecificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bd_auto1`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_auto1`.`usuario` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(45) NULL DEFAULT NULL,
  `senha` VARCHAR(10) NULL DEFAULT NULL,
  `email` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
